### ISSUE TITLE
Base class inference for specs is confusing and poorly documented

### ISSUE THREAD

**Issue by adammck** [minitest/minitest-rails#126]
Please excuse this long-winded issue. I'm trying to explain the problem (as I see it) as clearly as possible, because it's not a bug as such, more of an edge-case which I think should be clarified. I wasted a lot of time figuring it out this morning, and am hoping to spare others the trouble.

The README states that:

> Your test will continue to inherit from ActiveSupport::TestCase, which will now support the spec DSL.

And from the generated `test_helper.rb`:

```
class ActiveSupport::TestCase
  # Add more helper methods to be used by all tests here...
end
```

This led me to believe that using minitest-rails would be a similar experience to writing [vanilla Rails tests](http://edgeguides.rubyonrails.org/testing.html) with AS::TC, which I like, but with the spec syntax, which my team likes. So I assumed that the following would work:

```
describe Something do
  it "can do stuff" do
    w = Whatever.create!(name: "whatever")
    Something.new.do_stuff(w)
  end
end
```

But it doesn't, because `Something` is a PORO, not a model, view, controller, or mailer. [Those classes are special](https://github.com/blowmage/minitest-rails/blob/master/lib/minitest/rails.rb), and their specs are correctly set to inherit from AS::TC. For all other classes, the base class is **not** set, and it falls back to `MiniTest::Spec`.

The most obvious side-effect of this is that when testing a PORO like `Something`, transactional fixtures don't work, which can lead to intermittent failures and order-dependent tests. But also those helper methods defined in `test_helper.rb` aren't available, and any setup/teardown hooks defined there aren't fired.

Outside of Rails, this is all fine. But in a Rails test suite, that inconsistency can be very surprising and confusing. Especially since the documentation doesn't mention it anywhere.
## 

My preferred solution to this would be to make `ActiveSupport::TestCase` the default base class for all MiniTest specs when this gem is in use, but I understand that could break existing tests and would upset hypothetical users who expect this behavior. I'd be happy to submit a pull request if this is something you'd consider.

What do you think?

**Comment by HuckyDucky** [comment]
Where exactly does such a line:

    MiniTest::Spec::TYPES[0][1] = ActiveSupport::TestCase

go? In my ```test_helper.rb```? I fail to understand how this makes POROs be test with AS::TC. I am unable to test POROs unless I subclass ActiveRecord::Base. Which is more of a hack that this even is. 10 hours I've been screwing with this now.

**Comment by blowmage** [comment]
The `MiniTest::Spec::TYPES[0][1] = ActiveSupport::TestCase` thing is a hack. Don't do it. Here is the issue, if you don't register a spec type for whatever you are testing, it will default to using `Minitest::Spec` as the test class. This doesn't support the database transaction, so you can't connect to the database in your test. This generally sucks if you are on Rails 4.0 or earlier. 

However, if you are on Rails 4.1 or later, you are using Minitest 5 and can use the additional describe arguments. This means with minitest-rails installed you can do the following:

```ruby
describe MyPoro, :model do
  it "connects to the database" do
    my_user = users :admin # fixtures too!
  end
end
```

I'm sorry you have struggled with this. Next time hit me up on twitter or gitter or wherever and I'll try to help.

**Comment by HuckyDucky** [comment]
Hey Mike, thanks a *lot*! It worked instantly. I really appreciate your help. That's so much cleaner.

**Comment by zenspider** [comment]
> On Jun 25, 2015, at 13:02, HuckyDucky <notifications@github.com> wrote:
> 
> 10 hours I've been screwing with this now.

Next time? Please stop and ask at 1. Or even 1/2.

**Comment by HuckyDucky** [comment]
I did, just everywhere but here.

**Comment by blowmage** [comment]
You always find things in the last place you look. :)
