### ISSUE TITLE
Minitest-rails 2.0.1 InvalidAuthenticityToken

### ISSUE THREAD

**Issue by danielstocks** [minitest/minitest-rails#147]
Hello!

I was previously using 2.0.0.beta1 with a Rails 4.1.0 Project and everything was working perfectly well. 

After upgrading minitest-rails to 2.0.1 I started getting these errors in controller tests:

```
ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken
```

I checked to make sure that the ENV["rails_env"] is set to "test" and it is, so I'm not sure what the problem is here. Anyways, I reverted back to 2.0.0.beta1 and it's working again.

Any idea what might be causing this?

Cheers

**Comment by smtlaissezfaire** [comment]
FYI I ran into this when running tests with TESTOPTS through spring.  See https://github.com/rails/spring/issues/567
