### ISSUE TITLE
Can't run individual tests with minitest-rails

### ISSUE THREAD

**Issue by rmm5t** [minitest/minitest-rails#153]
The new convention for running an individual test in Rails 4.1 is something like:

```
bin/rake test test/models/account_test.rb
```

When minitest-rails is introduced, the entire test suite is run every time, which is undesirable, especially when a default setup for guard and spring is also introduced.

**Comment by artempartos** [comment]
you can try gem minitest-failed for run only failed tests. https://github.com/artempartos/minitest-failed
