### ISSUE TITLE
404: Page not found for blowmage.com/minitest-rails

### ISSUE THREAD

**Issue by VSPPedro** [minitest/minitest-rails#244]
Hi there, thank you for this awesome gem.

It seems to me that there is a problem with this gem's website. - [link](https://blowmage.com/minitest-rails) - result:

![Screenshot from 2022-07-21 10-55-20](https://user-images.githubusercontent.com/18314910/180231318-01f290f3-e570-4fb8-8a9c-c471adc28029.png)

I am creating this issue in case no one has noticed this detail. Thanks again

**Comment by blowmage** [comment]
This has been fixed. Thanks for the report!
