### ISSUE TITLE
Missing `test` method

### ISSUE THREAD

**Issue by tomprats** [minitest/minitest-rails#247]
Previously in minitest-rails 3.x we could do `test "something" do` instead of using `it`

I believe it came from `ActiveSupport::Test::Case` including [this file](https://github.com/rails/rails/blob/6-1-stable/activesupport/lib/active_support/testing/declarative.rb).

It appears to still be present in Rails but when upgrading from Rails 5 to Rails 6 and minitest-rails 3 to minitest-rails 6, it no longer works.

I'm pretty okay with just changing all the uses from `test` to `it`, but it errors in an odd way, so I've been down a whole rabbit whole.

Instead of something like unknown method `test` it says:

> .../test/lib/some_helper_test.rb:11:in `test': wrong number of arguments (given 1, expected 2) (ArgumentError)

**Comment by blowmage** [comment]
You should still be able to use `"test"`, as that method is provided by Rails and not affected by minitest-rails AFAIK. Can you reproduce this in a clean app?

**Comment by tomprats** [comment]
It turns out that it may have been from the tests no longer inheriting from `ActiveSupport::TestCase` and instead inherited from Minitest
