### ISSUE TITLE
incompatible with rails 7.1

### ISSUE THREAD

**Issue by codykrieger** [minitest/minitest-rails#249]
The latest version of minitest-rails is pinned to `gem "rails", "~> 7.0.0"`, so it is unfortunately not usable with the Rails 7.1 release candidate out of the box.

I was able to fork minitest-rails and change to `gem "rails", "~> 7.1.0.rc1"`, and that seems to work.

Is there any reason why minitest-rails can't simply enforce a minimum version requirement (i.e. `gem "rails", ">= 7.0.0"`), rather than pinning to specific Rails versions? This is the only gem in our app, out of ~110 gems, that pins to a specific Rails version, making upgrading more painful than necessary.

I'm happy to submit a pull request for this change if it is welcome.

cc @blowmage

**Comment by sergioisidoro** [comment]
Rails 7.1 is now out of release candidate, and this is also the only thing preventing us from upgrading.

**Comment by blowmage** [comment]
Thanks for posting this. I have been focused on other things and unfortunately didn't realize Rails 7.1 had been released. Expect a 7.1 release very soon.

**Comment by blowmage** [comment]
> Is there any reason why minitest-rails can't simply enforce a minimum version requirement

I outline the rationale for how minitest-rails is versioned on [my blog](https://blowmage.com/2019/06/18/minitest-rails-releases#new-versions). The tl;dr is that since rails doesn't follow semver on minor version releases this gem opts to follow the rails versioning.

**Comment by blowmage** [comment]
[minitest-rails 7.1.0](https://rubygems.org/gems/minitest-rails/versions/7.1.0) is released.

Thank you for contributing to this issue. I wish I had seen it sooner and gotten the non-release candidate release... uh... released.
