### ISSUE TITLE
test not using Minitest::Spec as ancestor is missing described names in test filtering

### ISSUE THREAD

**Issue by grosser** [minitest/minitest-rails#256]
before matching Minitest::Spec:
```
describe "bar" do
  it "baz" do
    puts 1
  end
end
```

run via `ruby -n bar_test.rb 'bar#test_0001_baz'`

after matching ActiveSupport::TestCase:
```
describe "bar", :model do
  it "baz" do
    puts 1
  end
end
```

`ruby bar_test.rb -v` says the name is `bar::model#test_0001_baz`
but running `ruby bar_test.rb -n 'bar::model#test_0001_baz'` does not work
only `ruby bar_test.rb -n 'test_0001_baz'` does
this breaks running tests by line via [minitest-line](https://github.com/judofyr/minitest-line) because it correctly uses `bar::model#test_0001_baz`

also tried `Minitest::Spec::DSL::TYPES[0] = [//, ActiveSupport::TestCase]` and it has the same effect, the describe part is gone

**Comment by zenspider** [comment]
I'm not seeing it:
```
Run options: -v --seed 36863

# Running:

bar::model#test_0001_baz = 0.00 s = .
```
such that:
```
10081 $ ruby -Ilib bug_256.rb -n 'bar::model#test_0001_baz'
Run options: -n bar::model#test_0001_baz --seed 33196

# Running:

.

Finished in 0.000254s, 3937.0086 runs/s, 3937.0086 assertions/s.
```

**Comment by zenspider** [comment]
No response in 3 weeks. Closing.
