### ISSUE TITLE
No way to test lib/* by default

### ISSUE THREAD

**Issue by dlee** [minitest/minitest-rails#59]
There's no way to unit test code under `lib/*` since `TASKS` (in minitest.rake) doesn't include `lib`, and it doesn't make sense to stuff the tests into any of the other subdirectories.

Would it make sense to add `lib` to `TASKS`?

**Comment by kmcphillips** [comment]
Zombie thread, but I came across this. 

`MINITEST_TASKS` and `MiniTest::Rails::Testing.default_tasks` have both been removed.

Solution is to create a `lib/tasks/test.rake` file which includes:

```
Rails::TestTask.new("test:lib" => "test:prepare") do |t|
  t.pattern = "test/lib/**/*_test.rb"
end
Rake::Task["test:run"].enhance ["test:lib"]
```

**Comment by vedant1811** [comment]
As of rails 4.2, all tests in the test/ directory are loaded by default

**Comment by CheezItMan** [comment]
It's not automatically testing code in Rails 5.  How do we enable testing of the lib folder in Rails 5?

**Comment by blowmage** [comment]
@CheezItMan write a new rake task.
